version: '3.8'

services:
  puertocho-nlu:
    build: .
    container_name: puertocho-nlu
    ports:
      - "5001:5001"
    volumes:
      - ./server:/root/server
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - PYTHONUNBUFFERED=1
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    driver: bridge 