language: es
pipeline:
  # Componente base de spaCy (REQUERIDO)
  - name: SpacyNLP
    model: es_core_news_md

  # Tokenización usando spaCy para español
  - name: SpacyTokenizer

  # Características de spaCy para español
  - name: SpacyFeaturizer

  # Características de expresiones regulares
  - name: RegexFeaturizer

  # Características léxicas y sintácticas
  - name: LexicalSyntacticFeaturizer

  # Vectorización de conteo de palabras
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2

  # Vectorización de conteo de caracteres
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # Modelo BERT multilingüe para embeddings contextualizados
  - name: HFTransformersNLP
    model_name: "bert-base-multilingual-cased"
    model_weights: "bert-base-multilingual-cased"
    cache_dir: null

  # Clasificador DIET mejorado con BERT
  - name: DIETClassifier
    epochs: 200
    learning_rate: 0.0005
    transformer_dim: 768
    use_masked_language_model: true
    constrain_similarities: true
    entity_recognition: true
    intent_classification: true
    BILOU_flag: true

  # Mapeo de sinónimos de entidades
  - name: EntitySynonymMapper

  # Selector de respuestas (opcional para futuras funcionalidades)
  - name: ResponseSelector
    epochs: 100 